# Generated by Django 2.1 on 2018-08-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='f_alta',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
