#!usr/bin/python3
# -*- coding: utf-8 -*-

'''
Templates para AyA
'''

inicio_admin = "".join([
	'<table border="0">',
		'<tr>',
			'<td align="left" port="anuncio">Anuncios</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="gestion">Gestión comercial</td>',
		'</tr>',
		'<tr>',
			'<td align="left">Argumentario</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="">Consultas</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="tecnico">&emsp;Técnico</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="comercial">&emsp;Comerciales</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="legal">&emsp;Legales</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="fiscal">&emsp;Fiscales</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="financiero">&emsp;Financieras</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="llamada">Llamadas</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="contacto">Contactos</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="visita">Visitas</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="oferta">Ofertas</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="propiedad">Propiedades</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="usuario">Usuarios</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="delegacion">Delegaciones</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="operacion">Operaciones</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="litigio">Litigios</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="publicidad">Volcados</td>',
		'</tr>',
	'</table>',
])

# Legal y Fiscal
inicio_legal = "".join([
	'<table border="0" valign="top">',
		'<tr>',
			'<td align="left" port="consulta">Consultas</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="comercial">&emsp;Comerciales</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="legal">&emsp;Legales</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="fiscal">&emsp;Fiscales</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="financiero">&emsp;Financieras</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="propiedades">Propiedades</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="usuario">Usuarios</td>',
		'</tr>',
	'</table>'
])

inicio_finan = "".join([
	'<table border="0" valign="top">',
		'<tr>',
			'<td align="left" port="consulta">Consultas</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="legal">&emsp;Mi abogado</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="fiscal">&emsp;Mi fiscal</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="financiero">&emsp;Mi financiero</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="contacto">Contactos</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="operacion">Operaciones</td>',
		'</tr>',
	'</table>'
])


inicio_comer = "".join([
	'<table BORDER="0">',
		'<tr>',
			'<td align="left" port="anuncio">Anuncios</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="nuevo">&emsp;Nuevos</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="seguimiento">&emsp;En seguimiento</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="adelante">&emsp;Más adelante</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="tramite">&emsp;En trámite</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="no_contesta">&emsp;No contesta</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="contratado">&emsp;Contratados</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="no_interesa">&emsp;No interesa</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="descartados">&emsp;Descartados</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="argumentario">Argumentario</td>',
		'</tr><tr>',
			'<td align="left" port="litigio">Litigios</td>',
		'</tr>',
	'</table>'
])

inicio_coor = "".join([
	'<table border="0">',
		'<tr>',
			'<td align="left" port="anuncio">Anuncios</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="gestion">Gestión comercial</td>',
		'</tr>',
		'<tr>',
			'<td align="left">Argumentario</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="">Consultas</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="tecnico">&emsp;Técnico</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="comercial">&emsp;Comerciales</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="legal">&emsp;Legales</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="fiscal">&emsp;Fiscales</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="financiero">&emsp;Financieras</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="llamada">Llamadas</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="contacto">Contactos</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="visita">Visitas</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="oferta">Ofertas</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="propiedad">Propiedades</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="usuario">Usuarios</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="operacion">Operaciones</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="litigio">Litigios</td>',
		'</tr>',
	'</table>',
])

inicio_dele = "".join([
	'<table border="0">',
		'<tr>',
			'<td align="left" port="anuncio">Anuncios</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="panel">Panel de control</td>',
		'</tr>',
		'<tr>',
			'<td align="left">Argumentario</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="">Consultas</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="tecnico">&emsp;Técnico</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="comercial">&emsp;Comerciales</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="legal">&emsp;Legales</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="fiscal">&emsp;Fiscales</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="financiero">&emsp;Financieras</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="llamada">Llamadas</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="contacto">Contactos</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="visita">Visitas</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="oferta">Ofertas</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="propiedad">Propiedades</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="usuario">Usuarios</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="operacion">Operaciones</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="litigio">Litigios</td>',
		'</tr>',
	'</table>',
])

inicio_prop = "".join([
	'<table BORDER="0">',
		'<tr>',
			'<td ALIGN="LEFT">Panel de control</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="consulta">Consultas</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="comercial">&emsp;Comerciales</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="legal">&emsp;Legales</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="fiscal">&emsp;Fiscales</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="llamadas">Llamadas</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="visitas">Visitas</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="ofertas">Ofertas</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="usuario">Mis datos</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="propiedad">Mi propiedad</td>',
		'</tr>',
	'</table>',
])

inicio_comp = "".join([
	'<table BORDER="0">',
		'<tr>',
			'<td align="left" port="credito">Mi crédito</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="consulta">Consultas</td>',
		'</tr><tr>',
			'<td align="left" port="legal">&emsp;Mi abogado</td>',
		'</tr><tr>',
			'<td align="left" port="fiscal">&emsp;Mi fiscal</td>',
		'</tr><tr>',
			'<td align="left" port="financiero">&emsp;Mi financiero</td>',
		'</tr><tr>',
			'<td align="left" port="usuario">Mis datos</td>',
		'</tr>',
	'</table>'
])

inicio_comer_finan = "".join([
	'<table border="0" valign="top">',
		'<tr>',
			'<td align="left" port="contacto">Contactos</td>',
		'</tr>',
		'<tr>',
			'<td align="left" port="operacion">Operaciones</td>',
		'</tr>',
	'</table>'
])

inicio_liti = "".join([
	'<table BORDER="0">',
		'<tr>',
			'<td align="left" port="litigio">Litigios</td>',
		'</tr>',
	'</table>'
])

imagen = "".join([
	'<table border="0">',

	"</table>"
])


def devuelve_template(titulo_template, titulo = False):

	if titulo:

		label = titulo_template.replace('_', ' ')
	
		label = label.capitalize()

		tabla = "".join([
			"<table border='0'>",
				"<tr>",
					"<td></td>",
					'<td port="titulo_arriba"></td>',
					"<td></td>",
				"</tr>",
				"<tr>",
					"<td colspan='3'>" + label + "</td>",
				"</tr>",
				"<tr>",
					"<td></td>",
					'<td port="titulo_abajo"></td>',
					"<td></td>",
				"</tr>",
			"</table>"	
		])

		return tabla

	else:

		return eval(titulo_template)






